### ISSUE TITLE
Crash with char * as NULL

### ISSUE THREAD

**Issue by eerimoq** [vberlier/narwhal#10]
Hello!

Calling `ASSERT_EQ(char *, char *)` with one of both parameters as `NULL` fails as below when the address sanitizer enabled. I suggest just comparing the pointers if one or both are `NULL`.

Test program:

``` c
#include "narwhal.h"

TEST(test)
{
    ASSERT_EQ(NULL, NULL);
    printf("void OK\n");

    ASSERT_EQ((char *)NULL, (char *)NULL);
    printf("char OK\n");
}
```

Build and run:

``` text
$ cc -fsanitize=address main.c narwhal.c && ./a.out

Running tests...

     1 - 1 |  F

Test results:

    FAIL test (16.81ms)

Failing tests:

    test failed:

        Location: main.c:3
        Time:     16.81ms
        Error:    Test process exited unexpectedly.

        Output:

         1 |  void OK
         2 |  AddressSanitizer:DEADLYSIGNAL
         3 |  =================================================================
         4 |  ==12194==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f872d3772cc bp 0x7ffd9ac4f790 sp 0x7ffd9ac4eef0 T0)
         5 |  ==12194==The signal is caused by a READ memory access.
         6 |  ==12194==Hint: address points to the zero page.
         7 |      #0 0x7f872d3772cb  (/lib/x86_64-linux-gnu/libasan.so.5+0xd52cb)
         8 |      #1 0x56064af942f3 in narwhal_check_string_equal (/home/erik/workspace/ntest/a.out+0x122f3)
         9 |      #2 0x56064af86769 in _narwhal_test_function_test (/home/erik/workspace/ntest/a.out+0x4769)
        10 |      #3 0x56064af8990a in execute_test_function (/home/erik/workspace/ntest/a.out+0x790a)
        11 |      #4 0x56064af8a438 in narwhal_run_test (/home/erik/workspace/ntest/a.out+0x8438)
        12 |      #5 0x56064af92c97 in narwhal_test_session_run_test (/home/erik/workspace/ntest/a.out+0x10c97)
        13 |      #6 0x56064af92d10 in narwhal_test_session_run_parameterized_test (/home/erik/workspace/ntest/a.out+0x10d10)
        14 |      #7 0x56064af93061 in narwhal_test_session_run_test_group (/home/erik/workspace/ntest/a.out+0x11061)
        15 |      #8 0x56064af937cf in narwhal_run_root_group (/home/erik/workspace/ntest/a.out+0x117cf)
        16 |      #9 0x56064af8e8e7 in main (/home/erik/workspace/ntest/a.out+0xc8e7)
        17 |      #10 0x7f872d0ddb6a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26b6a)
        18 |      #11 0x56064af86489 in _start (/home/erik/workspace/ntest/a.out+0x4489)
        19 |  
        20 |  AddressSanitizer can not provide additional info.
        21 |  SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libasan.so.5+0xd52cb) 
        22 |  ==12194==ABORTING
        23 |  

Tests: 1 failed, 0 passed, 1 total
Time:  17.37ms
```

**Comment by vberlier** [comment]
Thanks for the heads up! Just fixed it in v0.4.8.
